### ISSUE TITLE
Add tab that lists the current registrations to the event management

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/Gandalf#52]
- [x] Add the tab ( #48 )
- [x] Create the lists ( #48 )
- [x] ~~Add Cancan restrictions~~ ( #144 )
- [x] Add paid checkbox with save button so an admin can't mistakenly click ( #53 )
